version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    build: src
    container_name: src-sdk-test
    volumes:
      - ./scripts:/scripts
      - ./src:/var/www/html
      - ./config:/config
      - ./src/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf

    networks:
      - dinonet
      - default
networks:
  dinonet:
    external: true
